package translate

var defaultTexts = map[Locale]map[string]string{
	LocaleRussian: {
		"bad_request":                     "Неверный запрос",
		"unauthorized":                    "Не авторизован",
		"payment_required":                "Требуется оплата",
		"forbidden":                       "Запрещено",
		"not_found":                       "Не найдено",
		"method_not_allowed":              "Метод не разрешен",
		"not_acceptable":                  "Неприемлемо",
		"proxy_auth_required":             "Требуется аутентификация прокси",
		"timeout":                         "Таймаут",
		"conflict":                        "Конфликт",
		"gone":                            "Удалено",
		"length_required":                 "Необходима длина",
		"precondition_failed":             "Предусловие не выполнено",
		"entity_too_large":                "Сущность слишком большая",
		"uri_too_long":                    "URI слишком длинный",
		"unsupported_media_type":          "Неподдерживаемый тип медиа",
		"range_not_satisfiable":           "Диапазон не удовлетворяется",
		"expectation_failed":              "Ожидание не выполнено",
		"teapot":                          "Я чайник",
		"misdirected_request":             "Неправильно направленный запрос",
		"unprocessable_entity":            "Необрабатываемая сущность",
		"locked":                          "Заблокировано",
		"failed_dependency":               "Невыполненная зависимость",
		"too_early":                       "Слишком рано",
		"upgrade_required":                "Требуется обновление",
		"precondition_required":           "Требуется предусловие",
		"too_many_requests":               "Слишком много запросов",
		"request_header_fields_too_large": "Поля заголовка запроса слишком большие",
		"unavailable_for_legal_reasons":   "Недоступно по юридическим причинам",

		"internal":                       "Внутренняя ошибка сервера",
		"not_implemented":                "Не реализовано",
		"bad_gateway":                    "Плохой шлюз",
		"service_unavailable":            "Сервис недоступен",
		"gateway_timeout":                "Таймаут шлюза",
		"http_version_not_supported":     "Версия HTTP не поддерживается",
		"variant_also_negotiates":        "Вариант также согласовывается",
		"insufficient_storage":           "Недостаточно хранилища",
		"loop_detected":                  "Обнаружен цикл",
		"not_extended":                   "Не расширено",
		"network_authentication__failed": "Сетевая аутентификация не удалась",

		"route_not_found":    "Путь не найден",
		"path_param_empty":   "Параметр обязателен",
		"request_parse_body": "Ошибка чтения тела запроса",
		"server_start":       "Ошибка запуска сервера",

		"validator.model": "Ошибка валидации модели",

		"translate.key_not_found": "Ключ перевода не найден",

		"auth.no_token":           "Отутствует токен авторизации",
		"auth.no_access":          "Нет доступа",
		"auth.no_groups":          "Отутствуют группы авторизации",
		"auth.invalid_groups":     "Неверные группы авторизации",
		"auth.resource_forbidden": "Доступ к ресурсу ограничен",
	},

	LocaleEnglish: {
		"bad_request":                     "Bad request",
		"unauthorized":                    "Unauthorized",
		"payment_required":                "Payment required",
		"forbidden":                       "Forbidden",
		"not_found":                       "Not found",
		"method_not_allowed":              "Method not allowed",
		"not_acceptable":                  "Not acceptable",
		"proxy_auth_required":             "Proxy authentication required",
		"timeout":                         "Timeout",
		"conflict":                        "Conflict",
		"gone":                            "Gone",
		"length_required":                 "Length required",
		"precondition_failed":             "Precondition failed",
		"entity_too_large":                "Entity too large",
		"uri_too_long":                    "URI too long",
		"unsupported_media_type":          "Unsupported media type",
		"range_not_satisfiable":           "Range not satisfiable",
		"expectation_failed":              "Expectation failed",
		"teapot":                          "I'm a teapot",
		"misdirected_request":             "Misdirected request",
		"unprocessable_entity":            "Unprocessable entity",
		"locked":                          "Locked",
		"failed_dependency":               "Failed dependency",
		"too_early":                       "Too early",
		"upgrade_required":                "Upgrade required",
		"precondition_required":           "Precondition required",
		"too_many_requests":               "Too many requests",
		"request_header_fields_too_large": "Request header fields too large",
		"unavailable_for_legal_reasons":   "Unavailable for legal reasons",

		"internal":                       "Internal server error",
		"not_implemented":                "Not implemented",
		"bad_gateway":                    "Bad gateway",
		"service_unavailable":            "Service unavailable",
		"gateway_timeout":                "Gateway timeout",
		"http_version_not_supported":     "HTTP version not supported",
		"variant_also_negotiates":        "Variant also negotiates",
		"insufficient_storage":           "Insufficient storage",
		"loop_detected":                  "Loop detected",
		"not_extended":                   "Not extended",
		"network_authentication__failed": "Network authentication failed",

		"route_not_found":    "Route not found",
		"path_param_empty":   "Parameter is required",
		"request_parse_body": "Parse request body error",
		"server_start":       "Start server error",

		"validator.model": "Model validation error",

		"translate.key_not_found": "Translation key not found",

		"auth.no_token":           "No authorization token",
		"auth.no_access":          "No access",
		"auth.no_groups":          "No authorization groups",
		"auth.invalid_groups":     "Wrong authorization groups",
		"auth.resource_forbidden": "Access to resource is limited",
	},

	LocaleKazakh: {
		"bad_request":                     "Жарамсыз сұраныс",
		"unauthorized":                    "Авторизацияланбаған",
		"payment_required":                "Төлем қажет",
		"forbidden":                       "Тыйым салынған",
		"not_found":                       "Табылмады",
		"method_not_allowed":              "Әдіске рұқсат жоқ",
		"not_acceptable":                  "Қабылданбайды",
		"proxy_auth_required":             "Прокси аутентификациясы қажет",
		"timeout":                         "Күту уақыты аяқталды",
		"conflict":                        "Қақтығыс",
		"gone":                            "Кеткен",
		"length_required":                 "Ұзындық қажет",
		"precondition_failed":             "Алдын ала шарт орындалмады",
		"entity_too_large":                "Объект тым үлкен",
		"uri_too_long":                    "URI тым ұзын",
		"unsupported_media_type":          "Қолдау көрсетілмейтін медиа түрі",
		"range_not_satisfiable":           "Ауқым қанағаттандырылмайды",
		"expectation_failed":              "Күту орындалмады",
		"teapot":                          "Мен шәйнекпін",
		"misdirected_request":             "Қате бағытталған сұраныс",
		"unprocessable_entity":            "Өңделмейтін объект",
		"locked":                          "Құлыпталған",
		"failed_dependency":               "Тәуелділік қатесі",
		"too_early":                       "Тым ерте",
		"upgrade_required":                "Жаңарту қажет",
		"precondition_required":           "Алдын ала шарт қажет",
		"too_many_requests":               "Тым көп сұраныстар",
		"request_header_fields_too_large": "Сұраныс тақырыбының өрістері тым үлкен",
		"unavailable_for_legal_reasons":   "Заңды себептер бойынша қолжетімсіз",

		"internal":                       "Сервердің ішкі қатесі",
		"not_implemented":                "Іске асырылмаған",
		"bad_gateway":                    "Жаман шлюз",
		"service_unavailable":            "Қызмет қолжетімсіз",
		"gateway_timeout":                "Шлюз күту уақыты бітті",
		"http_version_not_supported":     "HTTP нұсқасына қолдау көрсетілмейді",
		"variant_also_negotiates":        "Нұсқа да келіссөздер жүргізеді",
		"insufficient_storage":           "Жеткіліксіз сақтау орны",
		"loop_detected":                  "Цикл анықталды",
		"not_extended":                   "Кеңейтілмеген",
		"network_authentication__failed": "Желілік аутентификация сәтсіз аяқталды",

		"route_not_found":    "Жол табылмады",
		"path_param_empty":   "Параметр қажет",
		"request_parse_body": "Талдау сұрауының негізгі қатесі",
		"server_start":       "Серверді іске қосу қатесі",

		"validator.model": "Модельді тексеру қатесі",

		"translate.key_not_found": "Аударма кілті табылмады",

		"auth.no_token":           "Рұқсат белгісі жоқ",
		"auth.no_access":          "Кіру жоқ",
		"auth.no_groups":          "Рұқсат ету топтары жоқ",
		"auth.invalid_groups":     "Қате авторизация топтары",
		"auth.resource_forbidden": "Ресурсқа қолжетімділік шектеулі",
	},
}
